#!/bin/bash
sudo yum update -y
sudo yum install python3 -y
python3 --version
python3 -m pip install --user virtualenv
python3 -m virtualenv myvirtualenv
pip3 install django
source myvirtualenv/bin/activate
pip install -r requirements.txt