#!/bin/bash
date
ls
sudo yum update -y
sudo yum install python3 -y
python3 --version
python3 -m pip install --user virtualenv
python3 -m virtualenv myvirtualenv
pip install --upgrade django-crispy-forms -y
pip3 install django